# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WYUtilCore_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WYUtilCore_Example
	pod 'WYUtilCore', :path => '../'

  target 'WYUtilCore_ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
